from dataclasses import dataclass
from enum import Enum

__all__ = [
    "TradeAction",
    "TradeSignal",
    "TradingMode",
    "generate_signal",
]


class TradeAction(Enum):
    """
    An enumeration class for trade actions.
    """

    BUY = "LONG"
    SELL = "SHORT"
    LONG = "LONG"
    SHORT = "SHORT"
    BMKT = "BMKT"
    SMKT = "SMKT"
    BLMT = "BLMT"
    SLMT = "SLMT"
    BSTP = "BSTP"
    SSTP = "SSTP"
    BSTPLMT = "BSTPLMT"
    SSTPLMT = "SSTPLMT"
    EXIT = "EXIT"
    EXIT_LONG = "EXIT_LONG"
    EXIT_SHORT = "EXIT_SHORT"
    EXIT_STOP = "EXIT_STOP"
    EXIT_LIMIT = "EXIT_LIMIT"
    EXIT_LONG_STOP = "EXIT_LONG_STOP"
    EXIT_LONG_LIMIT = "EXIT_LONG_LIMIT"
    EXIT_SHORT_STOP = "EXIT_SHORT_STOP"
    EXIT_SHORT_LIMIT = "EXIT_SHORT_LIMIT"
    EXIT_LONG_STOP_LIMIT = "EXIT_LONG_STOP_LIMIT"
    EXIT_SHORT_STOP_LIMIT = "EXIT_SHORT_STOP_LIMIT"
    EXIT_PROFITABLES = "EXIT_PROFITABLES"
    EXIT_LOSINGS = "EXIT_LOSINGS"
    EXIT_ALL_POSITIONS = "EXIT_ALL_POSITIONS"
    EXIT_ALL_ORDERS = "EXIT_ALL_ORDERS"

    def __str__(self):
        return self.value


@dataclass()
class TradeSignal:
    """
    Represents a trading signal generated by a trading system or strategy.

    Notes
    -----
    Attributes:

    - id (int): A unique identifier for the trade signal or the strategy.
    - symbol (str): The trading symbol (e.g., stock ticker, forex pair, crypto asset).
    - action (TradeAction): The trading action to perform. Must be an instance of the ``TradeAction`` enum (e.g., BUY, SELL).
    - price (float, optional): The price at which the trade should be executed.
    - stoplimit (float, optional): A stop-limit price for the trade. Must not be set without specifying a price.
    - sl (float, optional): A stop loss price for the trade.
    - tp (float, optional): A take profit price for the trade.
    - comment (str, optional): An optional comment or description related to the trade signal.
    """

    id: int
    symbol: str
    action: TradeAction
    price: float = None
    stoplimit: float = None
    sl: float = None
    tp: float = None
    comment: str = None

    def __post_init__(self):
        if not isinstance(self.action, TradeAction):
            raise TypeError(
                f"action must be of type TradeAction, not {type(self.action)}"
            )
        if self.stoplimit is not None and self.price is None:
            raise ValueError("stoplimit cannot be set without price")

    def __repr__(self):
        return (
            f"TradeSignal(id={self.id}, symbol='{self.symbol}', action='{self.action.value}', "
            f"price={self.price}, stoplimit={self.stoplimit}, sl={self.sl}, tp={self.tp}, comment='{self.comment or ''}')"
        )


def generate_signal(
    id: int,
    symbol: str,
    action: TradeAction,
    price: float = None,
    stoplimit: float = None,
    sl: float = None,
    tp: float = None,
    comment: str = None,
) -> TradeSignal:
    """
    Generates a trade signal for MetaTrader 5.

    Args:
        id (int): Unique identifier for the trade signal.
        symbol (str): The symbol for which the trade signal is generated.
        action (TradeAction): The action to be taken (e.g., BUY, SELL).
        price (float, optional): The price at which to execute the trade.
        stoplimit (float, optional): The stop limit price for the trade.
        sl (float, optional): The stop loss price for the trade.
        tp (float, optional): The take profit price for the trade.
        comment (str, optional): Additional comments for the trade.

    Returns:
        TradeSignal: A TradeSignal object containing the details of the trade signal.
    """
    return TradeSignal(
        id=id,
        symbol=symbol,
        action=action,
        price=price,
        stoplimit=stoplimit,
        sl=sl,
        tp=tp,
        comment=comment,
    )


class TradingMode(Enum):
    BACKTEST = "BACKTEST"
    LIVE = "LIVE"

    def isbacktest(self) -> bool:
        return self == TradingMode.BACKTEST

    def islive(self) -> bool:
        return self == TradingMode.LIVE
