version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  environment: {cache: false}

python:
  install:
    - requirements: docs/requirements.txt
    
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

build:
  commands:
    - rm -rf _build/doctrees
    - sphinx-build -b html docs/ _build/html
