version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  # commands:
  #   - rm -rf _build/doctrees
  #   - sphinx-build -b html docs/ _build/html

python:
  install:
    - requirements: docs/requirements.txt
    
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

  
