from typing import NamedTuple


class AccountInfo(NamedTuple):
    assets: float
    balance: float
    commission_blocked: float
    company: str
    credit: float
    currency: str
    currency_digits: int
    equity: float
    fifo_close: bool
    leverage: int
    liabilities: float
    limit_orders: int
    login: int
    margin: float
    margin_free: float
    margin_initial: float
    margin_level: float
    margin_maintenance: float
    margin_mode: int
    margin_so_call: float
    margin_so_mode: int
    margin_so_so: float
    name: str
    profit: float
    server: str
    trade_allowed: bool
    trade_expert: bool
    trade_mode: int


class BookInfo(NamedTuple):
    price: float
    type: int
    volume: int
    volume_real: float


class OrderCheckResult(NamedTuple):
    balance: float
    comment: str
    equity: float
    margin: float
    margin_free: float
    margin_level: float
    profit: float
    request: 'TradeRequest'
    retcode: int


class OrderSentResult(NamedTuple):
    ask: float
    bid: float
    comment: str
    deal: int
    order: int
    price: float
    request: 'TradeRequest'
    request_id: int
    retcode: int
    retcode_external: int
    volume: float


class RateInfo(NamedTuple):
    close: float
    high: float
    low: float
    open: float
    real_volume: int
    spread: int
    tick_volume: int
    time: int


class SymbolInfo(NamedTuple):
    ask: float
    askhigh: float
    asklow: float
    bank: str
    basis: str
    bid: float
    bidhigh: float
    bidlow: float
    category: str
    chart_mode: int
    currency_base: str
    currency_margin: str
    currency_profit: str
    custom: bool
    description: str
    digits: int
    exchange: str
    expiration_mode: int
    expiration_time: int
    filling_mode: int
    formula: str
    isin: str
    last: float
    lasthigh: float
    lastlow: float
    margin_hedged: float
    margin_hedged_use_leg: bool
    margin_initial: float
    margin_maintenance: float
    name: str
    option_mode: int
    option_right: int
    option_strike: float
    order_gtc_mode: int
    order_mode: int
    page: str
    path: str
    point: float
    price_change: float
    price_greeks_delta: float
    price_greeks_gamma: float
    price_greeks_omega: float
    price_greeks_rho: float
    price_greeks_theta: float
    price_greeks_vega: float
    price_sensitivity: float
    price_theoretical: float
    price_volatility: float
    select: bool
    session_aw: float
    session_buy_orders: int
    session_buy_orders_volume: float
    session_close: float
    session_deals: int
    session_interest: float
    session_open: float
    session_price_limit_max: float
    session_price_limit_min: float
    session_price_settlement: float
    session_sell_orders: int
    session_sell_orders_volume: float
    session_turnover: float
    session_volume: float
    spread: int
    spread_float: bool
    start_time: int
    swap_long: float
    swap_mode: int
    swap_rollover3days: int
    swap_short: float
    ticks_bookdepth: int
    time: int
    trade_accrued_interest: float
    trade_calc_mode: int
    trade_contract_size: float
    trade_exemode: int
    trade_face_value: float
    trade_freeze_level: int
    trade_liquidity_rate: float
    trade_mode: int
    trade_stops_level: int
    trade_tick_size: float
    trade_tick_value: float
    trade_tick_value_loss: float
    trade_tick_value_profit: float
    visible: bool
    volume: int
    volume_limit: float
    volume_max: float
    volume_min: float
    volume_real: float
    volume_step: float
    volumehigh: int
    volumehigh_real: float
    volumelow: int
    volumelow_real: float


class TerminalInfo(NamedTuple):
    build: int
    codepage: int
    commondata_path: str
    community_account: bool
    community_balance: float
    community_connection: bool
    company: str
    connected: bool
    data_path: str
    dlls_allowed: bool
    email_enabled: bool
    ftp_enabled: bool
    language: str
    maxbars: int
    mqid: bool
    name: str
    notifications_enabled: bool
    path: str
    ping_last: int
    retransmission: float
    trade_allowed: bool
    tradeapi_disabled: bool


class TickInfo(NamedTuple):
    ask: float
    bid: float
    flags: int
    last: float
    time: int
    time_msc: int
    volume: int
    volume_real: float


class TradeDeal(NamedTuple):
    comment: str
    commission: float
    entry: int
    external_id: str
    fee: float
    magic: int
    order: int
    position_id: int
    price: float
    profit: float
    reason: int
    swap: float
    symbol: str
    ticket: int
    time: int
    time_msc: int
    type: int
    volume: float


class TradeOrder(NamedTuple):
    comment: str
    external_id: str
    magic: int
    position_by_id: int
    position_id: int
    price_current: float
    price_open: float
    price_stoplimit: float
    reason: int
    sl: float
    state: int
    symbol: str
    ticket: int
    time_done: int
    time_done_msc: int
    time_expiration: int
    time_setup: int
    time_setup_msc: int
    tp: float
    type: int
    type_filling: int
    type_time: int
    volume_current: float
    volume_initial: float


class TradePosition(NamedTuple):
    comment: str
    external_id: str
    identifier: int
    magic: int
    price_current: float
    price_open: float
    profit: float
    reason: int
    sl: float
    swap: float
    symbol: str
    ticket: int
    time: int
    time_msc: int
    time_update: int
    time_update_msc: int
    tp: float
    type: int
    volume: float


class TradeRequest(NamedTuple):
    action: int
    comment: str
    deviation: int
    expiration: int
    magic: int
    order: int
    position: int
    position_by: int
    price: float
    sl: float
    stoplimit: float
    symbol: str
    tp: float
    type: int
    type_filling: int
    type_time: int
    volume: float
